version: '3'
services:
  # FastAPI application
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-portofolio
    image: api-portofolio-image
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    #  depends_on:
    #    - mongo
    env_file:
      - .env
  # MongoDB
  #mongo:
  #  image: mongo:latest
  #  container_name: mongo-portofolio
  #  ports:
  #    - "27018:27017" # Map external 27018 to internal 27017
  #  volumes:
  #    - ./mongo-data:/data/db
