version: '3'
services:
  fastapi-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-portofolio
    image: api-portofolio-image
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
